spring:
  application:
    name: viewEats
  profiles:
    active: local

  datasource:
    url: jdbc:postgresql://localhost:5432/vieweats
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

youtube:
  api-key: ${youtube.api-key}
  application-name: viewEats

gemini:
  api-key: ${gemini.api-key}

kakao:
  api-key: ${kakao.api-key}